### PR TITLE
Add config option to disable Tiberium Ore Explosions

### PR DESCRIPTION
**Pull request by MastaC729**
On some servers such as the one I manage, it was requested and approved that Tiberium Ore not explode when mined. I figured I'd help out and write the code to at least disable the explosions via config.

I also added an additional feature. When the ore cannot explode, it becomes very easy to farm experience off of Tiberium Ore. Therefore, I added a check to BlockTiberium#getExpDrop that decreases the nextInt bound to 3 instead of ten when Tiberium Ore explosions are disabled. Obviously I could have added a config check for that as well, but I figured I'd let you guys handle that decision. That decrease was made for our server specifically, and I figured there may be other servers who won't want that easy experience farming method added as well. Let me know what you think.

### CODE REVIEW

**Comment by Zkaface** [comment]
@MastaC729 I added the explosions for lore. To be honest, I don't care if there is an explosion or not. So if you like, I will add a config for that, which includes an experience negation.

**Comment by MastaC729** [comment]
Ok, sounds good. Thanks for the consideration.

**Comment by CaptainSisko** [comment]
Will this pull request be getting merged?

The [issue that this fixes](https://github.com/TeamFRM/TAIGA/issues/115) is still present.

**Comment by IdleGandalf** [comment]
In the current state this will not be merged. I reviewed this PR a while ago and the author hasn't taken any action yet.

**Comment by IdleGandalf** [comment]
Closing due to inactivity.

**Pull request closed without merging**
